image: docker:latest

variables:
  IMAGE_NAME: "seydoucoder/simple-http-server"
  IMAGE_TAG: "v1.0"

services:
  - docker:dind

stages:
  - build
  - push

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

build:
  stage: build
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_NAME:latest

push:
  stage: push
  script:
    - docker push $IMAGE_NAME:$IMAGE_TAG
    - docker push $IMAGE_NAME:latest
