name: Docker CI/CD

on:
  push:
    branches:
      - main   # La pipeline s'exécute à chaque push sur la branche `main`

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Vérifier le code source
      - name: Checkout code
        uses: actions/checkout@v2

      # Étape 2 : Installer Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Étape 3 : Construire l'image Docker
      - name: Build Docker image
        run: |
          docker build -t simple-http-server .

      # Étape 4 : Taguer l'image Docker et la pousser vers DockerHub
      - name: Push to DockerHub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker tag simple-http-server $DOCKER_USERNAME/simple-http-server:v1.0
          docker push $DOCKER_USERNAME/simple-http-server:v1.0
