name: Docker CI/CD

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout code
        uses: actions/checkout@v2

     
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

     
      - name: Build Docker image
        run: |
          docker build -t simple-http-server .

     
      - name: Log in to DockerHub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run: echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin

     
      - name: Push to DockerHub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          docker tag simple-http-server $DOCKER_USERNAME/simple-http-server:v1.0
          docker push $DOCKER_USERNAME/simple-http-server:v1.0
